r"""Cyclic generalized-bicycle search stack over Z_m (prime m).

One module, two layers:

* **Construction** (bottom): the "designed-divisor" / "prime-lift" approach
  that produced the board's top kd^2/n codes (n ~ 670-680, k ~ 140-182,
  d ~ 64-90). n = 2m, H_X = [circ(a)|circ(b)], H_Z = [circ(b)^T|circ(a)^T],
  k = 2*deg(gcd(a, b, x^m-1)). Pick a divisor g(x) of x^m-1; draw a(x), b(x)
  as SPARSE codewords of the cyclic code with generator g(x) (multiples of
  g mod x^m-1), found by Prange search on the parity-check circulant.
* **Search** (divisor ideals -> fertile ideals -> build-and-screen), plus
  the board-advancing harness (dominance checks, deep confirmation, first
  advancing-code driver) and the sweep/find-advancing/confirm CLI.

Dependencies: research/kit/{css,surrogate}.py and the verify/ tree (both
committed upstream); numpy and sympy.

Provenance: this stack produced the generalized-bicycle wave merged in
PRs #1206-#1261 (hackathon #1155) and earlier GB records; distances are
upper bounds until the trusted gate (verify/validate_candidate.py) rules.
"""
import sys, os, json, time, itertools
import numpy as np
import sympy

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "kit"))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "verify"))
from css import verify_css, compute_k, rank, rref
from surrogate import distance_rand, lightest_logical


# ---------------------------------------------------------------------------
#  GF(2) polynomial helpers (coefficients little-endian: poly[0] = x^0 term)
# ---------------------------------------------------------------------------
def poly_mul(a, b):
    """Multiply two GF(2) polynomials (lists of 0/1, little-endian)."""
    r = [0] * (len(a) + len(b) - 1)
    for i, ai in enumerate(a):
        if ai:
            for j, bj in enumerate(b):
                r[i + j] ^= bj
    return r


def poly_mod(a, m):
    """a mod m over GF(2). m must be nonzero."""
    dm = len(m) - 1
    while dm > 0 and m[dm] == 0:
        dm -= 1
    m = m[: dm + 1]
    r = list(a)
    while len(r) >= len(m):
        shift = len(r) - len(m)
        if r[-1]:
            for j in range(len(m)):
                r[shift + j] ^= m[j]
        r.pop()
    return r


def poly_gcd(a, b):
    while any(b):
        a, b = b, poly_mod(a, b)
    return a


def poly_deg(a):
    d = len(a) - 1
    while d > 0 and a[d] == 0:
        d -= 1
    return d if (d > 0 or a[0]) else -1


def poly_to_int(a):
    v = 0
    for i, ai in enumerate(a):
        if ai:
            v |= (1 << i)
    return v


def int_to_poly(v, m=None):
    a = [int((v >> i) & 1) for i in range(v.bit_length())]
    if m is not None:
        a = a + [0] * (m - len(a))
    return a


# ---------------------------------------------------------------------------
#  Factor x^m - 1 over GF(2) via sympy
# ---------------------------------------------------------------------------
def factor_xn_minus_1(m):
    """Return the irreducible factors of x^m - 1 over GF(2), each as
    (poly_int, degree). poly_int is the integer encoding (little-endian)."""
    x = sympy.symbols("x")
    poly = sympy.Poly(x**m + 1, x, modulus=2)  # x^m - 1 == x^m + 1 over GF(2)
    factors = []
    for f, mult in sympy.factor_list(poly)[1]:
        coeffs = sympy.Poly(f, x, modulus=2).all_coeffs()[::-1]  # little-endian
        # normalize: strip leading zeros
        while len(coeffs) > 1 and coeffs[-1] == 0:
            coeffs.pop()
        p_int = poly_to_int(coeffs)
        deg = len(coeffs) - 1
        factors.append((p_int, deg))
    return factors


def poly_from_int(p_int, m):
    return int_to_poly(p_int, m)


# ---------------------------------------------------------------------------
#  Build a cyclic generalized-bicycle code
# ---------------------------------------------------------------------------
def circ(v):
    """Circulant matrix with first row v (length m)."""
    m = len(v)
    M = np.zeros((m, m), dtype=np.int8)
    for i in range(m):
        M[i] = np.roll(v, i)
    return M


def build_cyclic_gb(m, a, b):
    """Build HX, HZ for a cyclic generalized-bicycle code over Z_m.
    a, b are length-m 0/1 lists (the first-row supports of the circulants)."""
    A = circ(np.array(a, dtype=np.int8))
    B = circ(np.array(b, dtype=np.int8))
    HX = np.concatenate([A, B], axis=1)
    HZ = np.concatenate([B.T, A.T], axis=1)
    return HX, HZ


def k_from_ab(m, a, b):
    """k = 2 * deg(gcd(a(x), b(x), x^m - 1))."""
    xm1 = [1] + [0] * (m - 1) + [1]  # x^m + 1 = x^m - 1 over GF(2)
    g = poly_gcd(poly_gcd(a, b), xm1)
    return 2 * poly_deg(g)


# ---------------------------------------------------------------------------
#  Prange search: find sparse codewords in the ideal generated by g(x)
# ---------------------------------------------------------------------------
def parity_check_of_ideal(m, g_int):
    """Parity-check polynomial h = (x^m - 1)/g(x). Codewords of the cyclic
    code with generator g(x) are ker(circ(h))."""
    xm1 = [1] + [0] * (m - 1) + [1]
    g = int_to_poly(g_int, m)
    # trim trailing zeros of g down to its true degree
    while len(g) > 1 and g[-1] == 0:
        g.pop()
    gd = len(g) - 1
    # long division: h = (x^m - 1) / g
    h = [0] * (m + 1)
    rem = list(xm1)
    while poly_deg(rem) >= gd:
        shift = poly_deg(rem) - gd
        h[shift] = 1
        for j in range(len(g)):
            rem[shift + j] ^= g[j]
        # trim trailing zeros, keep at least length gd+1
        while len(rem) > gd + 1 and rem[-1] == 0:
            rem.pop()
    return h[:m]  # degree < m


def prange_sparse_words(m, g_int, weight_band, n_trials, seed=0, max_words=1000):
    """Find sparse codewords of the cyclic code with generator g(x) (i.e.
    sparse multiples of g(x) mod x^m - 1) via a randomized kernel search.

    Codewords are ker(circ(h)) where h = (x^m-1)/g(x). We take the kernel
    basis, then per trial do a random column permutation + RREF to get a
    different basis, and collect low-weight rows plus their pairwise sums.

    Returns a list of (support_tuple, weight) for distinct words found.
    """
    from css import kernel_basis
    h = parity_check_of_ideal(m, g_int)
    H = circ(np.array(h, dtype=np.int8))  # (m, m) parity check
    K = kernel_basis(H)  # rows span the codewords
    if K.size == 0:
        return []
    rng = np.random.default_rng(seed)
    words = {}
    lo, hi = weight_band
    for _ in range(n_trials):
        perm = rng.permutation(m)
        red = rref(K[:, perm])[0]
        w = red.sum(axis=1)
        # collect rows in band
        for i in np.where((w >= lo) & (w <= hi))[0]:
            v = np.zeros(m, dtype=np.int8)
            v[perm] = red[i]
            wt = int(v.sum())
            if lo <= wt <= hi:
                sup = tuple(sorted(np.where(v)[0]))
                if sup not in words:
                    words[sup] = wt
                    if len(words) >= max_words:
                        return list(words.items())
        # pairwise sums of the lightest rows (closes the gap to minima
        # realized only as short combinations)
        if red.shape[0] >= 2:
            light = np.argsort(w)[:min(10, red.shape[0])]
            sub = red[light]
            for i in range(len(light)):
                pr = (sub[i] + sub[i + 1:]) % 2
                if pr.size == 0:
                    continue
                pw = pr.sum(axis=1)
                for j in np.where((pw >= lo) & (pw <= hi))[0]:
                    v = np.zeros(m, dtype=np.int8)
                    v[perm] = pr[j]
                    wt = int(v.sum())
                    if lo <= wt <= hi:
                        sup = tuple(sorted(np.where(v)[0]))
                        if sup not in words:
                            words[sup] = wt
                            if len(words) >= max_words:
                                return list(words.items())
    return list(words.items())


if __name__ == "__main__":
    # Sanity: factor x^7 - 1 over GF(2) = (x+1)(x^3+x+1)(x^3+x^2+1)
    print("factors of x^7 - 1:", [(hex(p), d) for p, d in factor_xn_minus_1(7)])
    # Test the cyclic construction on a small example
    m = 7
    a = [1, 1, 0, 0, 0, 0, 0]  # 1 + x
    b = [1, 0, 1, 0, 0, 0, 0]  # 1 + x^2
    HX, HZ = build_cyclic_gb(m, a, b)
    print("css:", verify_css(HX, HZ), "n:", HX.shape[1])
    print("k (via rank):", compute_k(HX, HZ))
    print("k (via gcd):", k_from_ab(m, a, b))

def divisor_ideals(m, target_deg, max_ideals=100000, seed=0):
    """Enumerate divisor ideals of x^m - 1 of degree target_deg.

    Returns a list of (g_int, deg). For prime m with factors of degree d and
    the linear factor, a divisor is a subset of the degree-d factors (plus
    optionally the linear factor). We enumerate combinations of the right
    size directly.
    """
    import itertools
    facts = factor_xn_minus_1(m)
    lin = [p for p, d in facts if d == 1]
    big = [(p, d) for p, d in facts if d > 1]
    results = []
    seen = set()
    # Try: use_lin in {0,1}, choose k big factors so that k*avg + use_lin = target
    # Since all big factors have the same degree d for prime m, we need
    # k*d + use_lin == target_deg.
    d = big[0][1] if big else 0
    all_same = all(bd == d for _, bd in big)
    if all_same:
        for use_lin in ([0, 1] if lin else [0]):
            rem = target_deg - use_lin
            if rem < 0 or rem % d != 0:
                continue
            k = rem // d
            if k < 0 or k > len(big):
                continue
            for combo in itertools.combinations(range(len(big)), k):
                g_int = 1
                if use_lin:
                    g_int = poly_to_int(poly_mul(int_to_poly(g_int, 1), int_to_poly(lin[0], 1)))
                for idx in combo:
                    p, dd = big[idx]
                    g_int = poly_to_int(poly_mul(int_to_poly(g_int, target_deg), int_to_poly(p, dd)))
                if g_int in seen:
                    continue
                seen.add(g_int)
                results.append((g_int, target_deg))
                if len(results) >= max_ideals:
                    return results
        return results
    # General fallback: random subsets
    rng = np.random.default_rng(seed)
    attempts = 0
    while attempts < max_ideals and len(results) < 200:
        attempts += 1
        mask = rng.integers(0, 2, size=len(big))
        deg = sum(d for (p, d), bit in zip(big, mask) if bit)
        use_lin = 0
        if lin and (deg + 1 == target_deg):
            use_lin = 1
            deg += 1
        if deg != target_deg:
            continue
        g_int = 1
        if use_lin:
            g_int = poly_to_int(poly_mul(int_to_poly(g_int, 1), int_to_poly(lin[0], 1)))
        for (p, d), bit in zip(big, mask):
            if bit:
                g_int = poly_to_int(poly_mul(int_to_poly(g_int, deg), int_to_poly(p, d)))
        if g_int in seen:
            continue
        seen.add(g_int)
        results.append((g_int, target_deg))
    return results


def find_fertile_ideals(m, target_deg, weight_band, n_trials, n_ideals, seed=0,
                        min_words=2, max_words_per_ideal=30):
    """Find divisor ideals of degree target_deg that contain low-weight
    codewords. Returns list of (g_int, words) where words is a list of
    (weight, support_tuple)."""
    ideals = divisor_ideals(m, target_deg, max_ideals=n_ideals, seed=seed)
    fertile = []
    for i, (g_int, deg) in enumerate(ideals):
        words = prange_sparse_words(m, g_int, weight_band, n_trials,
                                    seed=seed + i, max_words=max_words_per_ideal)
        if len(words) >= min_words:
            fertile.append((g_int, words))
    return fertile


def build_and_screen(m, g_int, words, trials, seed=0, min_d=1, backend="fast", threads=4):
    """Build codes from pairs of words in the ideal and screen by distance.
    Returns list of (eff, n, k, d, a, b, w) sorted by eff desc."""
    results = []
    # dedup words by support; prange returns (support_tuple, weight)
    seen = set()
    uniq = []
    for sup, wt in words:
        if sup not in seen:
            seen.add(sup)
            uniq.append((sup, wt))
    # pair words (a, b) - try distinct pairs
    for i in range(len(uniq)):
        for j in range(i, len(uniq)):
            a, wta = uniq[i]
            b, wtb = uniq[j]
            av = np.zeros(m, dtype=np.int8); av[list(a)] = 1
            bv = np.zeros(m, dtype=np.int8); bv[list(b)] = 1
            HX, HZ = build_cyclic_gb(m, av.tolist(), bv.tolist())
            if not verify_css(HX, HZ):
                continue
            k = compute_k(HX, HZ)
            n = 2 * m
            w = max(wta + wtb, 2 * max(wta, wtb))
            d = distance_rand(HX, HZ, trials=trials, seed=seed + i * 100 + j,
                              backend=backend, threads=threads)
            if d == float("inf") or d < min_d:
                continue
            eff = k * d * d / n
            results.append({"eff": eff, "n": n, "k": k, "d": int(d),
                            "w": int(w), "a": list(a), "b": list(b),
                            "g_int": g_int})
    results.sort(key=lambda r: -r["eff"])
    return results


def load_board(weight_cap=None):
    """Load board entries from codes/*.json as plain (n, k, d, w) dicts.

    weight_cap filters to entries with check weight <= cap; None keeps all.
    """
    import glob
    entries = []
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    for f in glob.glob(os.path.join(root, "codes", "*.json")):
        try:
            doc = json.load(open(f))
        except Exception:
            continue
        n = doc.get("n")
        k = doc.get("k")
        d = (doc.get("distance") or {}).get("d")
        if not (n and k and d):
            continue
        w = 0
        for side in ("X", "Z"):
            for sup in doc.get("checks", {}).get(side, []):
                w = max(w, len(sup))
        if weight_cap is not None and w <= weight_cap:
            continue
        entries.append({"n": n, "k": k, "d": d, "w": w})
    return entries


def dominates(other, cand):
    """True if `other` dominates `cand` on (n down, k up, d up, w down)."""
    return (other["n"] <= cand["n"] and other["k"] >= cand["k"]
            and other["d"] >= cand["d"] and other["w"] <= cand["w"]
            and (other["n"] < cand["n"] or other["k"] > cand["k"]
                 or other["d"] > cand["d"] or other["w"] < cand["w"]))


def is_advancing(board, n, k, d, w):
    """True if (n, k, d, w) is nondominated by every entry in `board`."""
    return not any(dominates(o, {"n": n, "k": k, "d": d, "w": w})
                   for o in board)


def deep_confirm(m, a, b, trials=2000000, threads=4):
    """Deep-confirm a cyclic GB candidate built from supports a, b.

    The screening distance is an upper bound that can be inflated; run a
    deep randomized search (default 2M trials/side) and the lightest
    logical on each side. Returns (d_upper, w_x, w_z).
    """
    av = np.zeros(m, dtype=np.int8); av[list(a)] = 1
    bv = np.zeros(m, dtype=np.int8); bv[list(b)] = 1
    HX, HZ = build_cyclic_gb(m, av.tolist(), bv.tolist())
    print("css:", verify_css(HX, HZ), "n:", HX.shape[1], "k:", compute_k(HX, HZ))
    d = distance_rand(HX, HZ, trials=trials, seed=0, backend="fast",
                      threads=threads)
    print(f"deep distance search, {trials} trials per side: d <= {d}")
    wx, _ = lightest_logical(HX, HZ, trials=trials, seed=1)
    wz, _ = lightest_logical(HZ, HX, trials=trials, seed=2)
    print(f"X lightest <= {wx}, Z lightest <= {wz}")
    return int(d) if d != float("inf") else None, wx, wz


def find_advancing(m, target_deg, weight_cap=None, band=(8, 16),
                   prange_trials=60000, screen_trials=2000, deep_trials=50000,
                   start_ideal=0, n_ideals=60, seed=7, threads=4, stop=True,
                   out="research/candidates/advancing_find.json"):
    """Scan divisor ideals and stop at the first nondominated code.

    Generalized from the one-off driver: weight_cap selects the board cell
    (None = unrestricted weight-9plus), and a survivor is deepened before
    it is reported, since the 2k screen often inflates d.
    """
    board = load_board(weight_cap)
    print(f"loaded {len(board)} board entries "
          f"({'w>=%d' % weight_cap if weight_cap else 'unrestricted'})")
    ideals = divisor_ideals(m, target_deg, max_ideals=100000, seed=seed)
    print(f"{len(ideals)} degree-{target_deg} ideals available (n={2*m})")
    t0 = time.time()
    for i in range(start_ideal, min(start_ideal + n_ideals, len(ideals))):
        g_int, deg = ideals[i]
        words = prange_sparse_words(m, g_int, band, prange_trials,
                                    seed=1000 + i, max_words=20)
        if len(words) < 2 or min(w for _, w in words) > 20:
            continue
        words_sorted = sorted(words, key=lambda x: x[1])
        for pi in range(min(4, len(words_sorted))):
            for pj in range(pi + 1, min(5, len(words_sorted))):
                (a, wta), (b, wtb) = words_sorted[pi], words_sorted[pj]
                w = max(wta + wtb, 2 * max(wta, wtb))
                if w > 32:
                    continue  # schema caps check weight at 32
                av = np.zeros(m, dtype=np.int8); av[list(a)] = 1
                bv = np.zeros(m, dtype=np.int8); bv[list(b)] = 1
                HX, HZ = build_cyclic_gb(m, av.tolist(), bv.tolist())
                if not verify_css(HX, HZ):
                    continue
                k = compute_k(HX, HZ)
                n = 2 * m
                d = distance_rand(HX, HZ, trials=screen_trials, seed=0,
                                  backend="fast", threads=threads)
                if d == float("inf"):
                    continue
                adv = is_advancing(board, n, k, int(d), w)
                print(f"[{time.time()-t0:.0f}s] ideal {i} pair({pi},{pj}): "
                      f"[[{n},{k},{int(d)}]] w={w} "
                      f"eff={k*d*d/n:.1f} advancing={adv}", flush=True)
                if not adv:
                    continue
                d2 = distance_rand(HX, HZ, trials=deep_trials, seed=1,
                                   backend="fast", threads=threads)
                if d2 == float("inf"):
                    continue
                adv2 = is_advancing(board, n, k, int(d2), w)
                print(f"  deepened: d<={int(d2)} eff={k*d2*d2/n:.1f} "
                      f"advancing={adv2}", flush=True)
                if not adv2:
                    continue
                result = {"n": int(n), "k": int(k), "d": int(d2), "w": int(w),
                          "eff": round(float(k*d2*d2/n), 2),
                          "a": [int(x) for x in a], "b": [int(x) for x in b],
                          "g_int": int(g_int)}
                if out:
                    os.makedirs(os.path.dirname(out), exist_ok=True)
                    json.dump(result, open(out, "w"), indent=1)
                    print(f"saved to {out}")
                if stop:
                    return result
    print(f"no advancing code in ideals {start_ideal}..{start_ideal + n_ideals - 1} "
          f"({time.time()-t0:.0f}s)")
    return None


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--m", type=int, default=337)
    ap.add_argument("--deg", type=int, default=85)
    ap.add_argument("--band", type=str, default="14-16")
    ap.add_argument("--ideals", type=int, default=50)
    ap.add_argument("--trials", type=int, default=2000)
    ap.add_argument("--screen", type=int, default=400)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out", type=str, default="research/candidates/cyclic_search.json")
    ap.add_argument("--backend", type=str, default="fast")
    ap.add_argument("--threads", type=int, default=4)
    ap.add_argument("--mode", choices=("sweep", "find-advancing", "confirm"),
                    default="sweep")
    ap.add_argument("--weight-cap", type=int, default=None,
                    help="board cell filter: keep entries with w > cap "
                         "(find-advancing mode only)")
    ap.add_argument("--confirm", type=str, default=None,
                    help="candidate JSON with n, a, b (confirm mode only)")
    ap.add_argument("--confirm-trials", type=int, default=2000000)
    ap.add_argument("--campaign", type=str, default=None,
                    help="campaign.json whose run_contract supplies m, deg, "
                         "band, ideals, trials, screen, seed and threads; an "
                         "explicit flag still wins but is reported as a "
                         "deviation from the contract")
    args = ap.parse_args()

    # A sweep whose depth lives only in argv leaves nothing that says what it
    # ran at, and two distances read at different budgets are not comparable.
    # With a campaign file the contract supplies the depth; the flags stay
    # usable, and a departure from the contract is printed rather than
    # absorbed, so it reaches the run's own log and from there the note.
    if args.campaign:
        sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "kit"))
        from campaign import load_campaign  # noqa: PLC0415
        camp = load_campaign(args.campaign)
        if not camp.run_contract:
            sys.exit(f"{args.campaign}: no run_contract to read parameters "
                     "from; add one or drop --campaign")
        given = {a.dest for a in ap._actions
                 if any(f in sys.argv for f in a.option_strings)}
        params, deviations = camp.resolved_params(
            **{k: getattr(args, k) for k in given
               if k in (camp.run_contract["parameters"] or {})})
        for key, value in params.items():
            if hasattr(args, key):
                setattr(args, key, value)
        print(f"campaign {camp.id}, contract {camp.contract_hash}: "
              + " ".join(f"{k}={v}" for k, v in sorted(params.items())))
        for key, d in sorted(deviations.items()):
            print(f"  deviation: {key} contract={d['contract']} used={d['used']}")

    lo, hi = map(int, args.band.split("-"))

    if args.mode == "confirm":
        cand = json.load(open(args.confirm))
        m_c = cand["n"] // 2
        deep_confirm(m_c, cand["a"], cand["b"], trials=args.confirm_trials,
                     threads=args.threads)
        sys.exit(0)

    if args.mode == "find-advancing":
        find_advancing(args.m, args.deg, weight_cap=args.weight_cap,
                       band=(lo, hi), screen_trials=args.screen,
                       seed=args.seed, threads=args.threads)
        sys.exit(0)

    t0 = time.time()
    fertile = find_fertile_ideals(args.m, args.deg, (lo, hi), args.trials,
                                  args.ideals, seed=args.seed)
    print(f"[{time.time()-t0:.0f}s] {len(fertile)} fertile ideals of degree {args.deg}")
    all_results = []
    for gi, words in fertile:
        res = build_and_screen(args.m, gi, words, args.screen, seed=args.seed,
                               backend=args.backend, threads=args.threads)
        all_results.extend(res)
    all_results.sort(key=lambda r: -r["eff"])
    print(f"[{time.time()-t0:.0f}s] {len(all_results)} codes screened")
    for r in all_results[:20]:
        print(f"  eff={r['eff']:8.1f} [[{r['n']},{r['k']},{r['d']}]] w={r['w']}")
    json.dump(all_results, open(args.out, "w"), indent=1)
    print(f"saved {len(all_results)} results to {args.out}")